jobs:
  build:
    docker:
      - image: google/cloud-sdk
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: touch ${HOME}/gcp-key.json
      - run:
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run:
          name: Build image
          command: docker build -t us.gcr.io/dsp-appsec-dev/example-app-test:${CIRCLE_SHA1} .
      - run: 
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run:
          name: Install trivy
          command: apk add --update-cache --upgrade --update curl | curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with trivy (light)
          command: trivy --exit-code 0 --no-progress example-app-test:${CIRCLE_SHA1}
      - run: 
          gcloud docker -- push us.gcr.io/dsp-appsec-dev/example-app-test:$CIRCLE_SHA1
workflows:
  version: 2
  release:
    jobs:
      - build
