name: Scan
on: [push, pull_request]
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build -t us.gcr.io/dsp-appsec-dev/example-app:latest .
    - name: Scan
      uses: docker://aquasec/trivy
      with:
        args: --exit-code 1 --severity CRITICAL,HIGH --no-progress us.gcr.io/dsp-appsec-dev/example-app
