name: Scan
on: [push, pull_request]
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build -t example-app:latest .
    - name: Scan
      uses: docker://aquasec/trivy
      with:
        args: --severity CRITICAL --no-progress example-app:latest
